### ISSUE TITLE
搜图接口请求403

### ISSUE THREAD

**Issue by KafuuEriri** [yhArcadia/ap-plugin#1]
日志
```
yunzai-bot    | [YzBot][18:47:40.506][ERRO] 【ap-plugin v2.11.3】 AxiosError: Request failed with status code 403
yunzai-bot    |     at settle (file:///app/Yunzai-Bot/plugins/ap-plugin/node_modules/axios/lib/core/settle.js:19:12)
yunzai-bot    |     at IncomingMessage.handleStreamEnd (file:///app/Yunzai-Bot/plugins/ap-plugin/node_modules/axios/lib/adapters/http.js:548:11)
yunzai-bot    |     at IncomingMessage.emit (node:events:525:35)
yunzai-bot    |     at endReadableNT (node:internal/streams/readable:1359:12)
yunzai-bot    |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
yunzai-bot    |   code: 'ERR_BAD_REQUEST',
yunzai-bot    |   config: {
yunzai-bot    |     transitional: {
yunzai-bot    |       silentJSONParsing: true,
yunzai-bot    |       forcedJSONParsing: true,
yunzai-bot    |       clarifyTimeoutError: false
yunzai-bot    |     },
yunzai-bot    |     adapter: [ 'xhr', 'http' ],
yunzai-bot    |     transformRequest: [ [Function: transformRequest] ],
yunzai-bot    |     transformResponse: [ [Function: transformResponse] ],
yunzai-bot    |     timeout: 0,
yunzai-bot    |     xsrfCookieName: 'XSRF-TOKEN',
yunzai-bot    |     xsrfHeaderName: 'X-XSRF-TOKEN',
yunzai-bot    |     maxContentLength: -1,
yunzai-bot    |     maxBodyLength: -1,
yunzai-bot    |     env: { FormData: [Function], Blob: [class Blob] },
yunzai-bot    |     validateStatus: [Function: validateStatus],
yunzai-bot    |     headers: AxiosHeaders {
yunzai-bot    |       Accept: 'application/json, text/plain, */*',
yunzai-bot    |       'Accept-Encoding': '*',
yunzai-bot    |       'User-Agent': 'axios/1.3.1'
yunzai-bot    |     },
yunzai-bot    |     method: 'get',
yunzai-bot    |     url: 'https://saucenao.com/search.php?output_type=2&numres=30&api_key=b63a59887160b1e3f442ec8d0633c4d80d8cdfac&url=https://gchat.qpic.cn/gchatpic_new/471881465/3928885573-2953701826-FBADBD8CF73FF94FFEFB855077D1371C/0?term=3&is_origin=1',
yunzai-bot    |     data: undefined
yunzai-bot    |   },
```
curl接口正常
```
# curl 'https://saucenao.com/search.php?output_type=2&numres=30&api_key=b63a59887160b1e3f442ec8d0633c4d80d8cdfac&url=https://c2cpicdw.qpic.cn/offpic_new/471881465//471881465-2927672844-FBADBD8CF73FF94FFEFB855077D1371C/0?term=3&is_origin=1'   -H 'authority: saucenao.com'   -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'   -H 'accept-language: zh-CN,zh;q=0.9,en;q=0.8'   -H 'cookie: token=63dcd3ace0486; user=98784; auth=05688f4c7c1a4c81cf9e7e20d82f162e7799211f'   -H 'sec-ch-ua: "Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"'   -H 'sec-ch-ua-mobile: ?0'   -H 'sec-ch-ua-platform: "macOS"'   -H 'sec-fetch-dest: document'   -H 'sec-fetch-mode: navigate'   -H 'sec-fetch-site: none'   -H 'sec-fetch-user: ?1'   -H 'upgrade-insecure-requests: 1'   -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36'   --compressed|jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1532    0  1532    0     0   1256      0 --:--:--  0:00:01 --:--:--  1256
{
  "header": {
    "user_id": "98784",
    "account_type": "1",
    "short_limit": "4",
    "long_limit": "100",
    "long_remaining": 91,
    "short_remaining": 3,
    "status": 0,
    "results_requested": "8",
    "index": {
      "0": {
        "status": 0,
        "parent_id": 0,
        "id": 0,
        "results": 8
      },
      "2": {
        "status": 0,
        "parent_id": 2,
        "id": 2,
        "results": 8
      },
```

**Comment by KafuuEriri** [comment]
发现问题是我浏览器有cookie所以可以正常请求，复制的curl带了cookie，这块功能应该把账号token带过来才能正常访问，晚点我调试提个pr吧
